const galleryTypes = {
    ADD_NEW_IMAGE_START: "ADD_NEW_IMAGE_START",
    FETCH_GALLERY_IMAGE_START: "FETCH_GALLERY_IMAGE_START",
    SET_GALLERY: "SET_GALLERY",
    CHANGE_GALLERY_IMAGE_START: "CHANGE_GALLERY_IMAGE_START",
    DELETE_GALLERY_IMAGE_START: "DELETE_GALLERY_IMAGE_START",
    FETCH_HOMEPAGE_DESCRIPTION: "FETCH_HOMEPAGE_DESCRIPTION",
    SET_HOMEPAGE_DESCRIPTION: "SET_HOMEPAGE_DESCRIPTION",
    UPDATE_HOMEPAGE_DESCRIPTION: "UPDATE_HOMEPAGE_DESCRIPTION"
};

export default galleryTypes;